import { Roboto } from "next/font/google";
import "./globals.css";



const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700', '500', '900'],
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {

  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <main> {children}</main>


      </body>
    </html>
  );
}
