"use client"
import { Roboto } from "next/font/google";
import { store } from "@/store/store"
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"
import "./globals.css";



const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700', '500', '900'],
  variable: '--font-roboto',
});

// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({ children }) {

  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Provider store={store}>

          <main> {children}</main>
        </Provider>

        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"

        />


      </body>
    </html>
  );
}
